filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/energy-devices/*.log

- type: mqtt
  enabled: true
  hosts:
    - "emqx:1883"
  topics:
    - "energy/+/data"
    - "energy/+/logs" 
    - "system/+/status"
  qos: 2
  client_id: "filebeat"
  clean_session: true

output.logstash:
  hosts: ["logstash:5044"]
