metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
  enabled: true
  period: 10s
  processes: ['.*']

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: mqtt
  metricsets: ["topic"]
  period: 10s
  hosts: ["emqx:1883"]
  username: "metricbeat"
  password: "metricbeat123"
  topics: ["energy/+/data", "system/+/metrics"]

output.logstash:
  hosts: ["logstash:5044"]
