http.host: 0.0.0.0
log.level: warn
pipeline.batch.delay: 50
pipeline.batch.size: 250
pipeline.unsafe_shutdown: false
pipeline.workers: 2
queue.max_bytes: 1gb
queue.max_events: 0
queue.type: memory
xpack.monitoring.enabled: false
